PYTHON3 ?= python3

check:
	$(PYTHON3) test_basic_command.py
	$(PYTHON3) test_usernamespace.py
	$(PYTHON3) test_utsnamespace.py
	$(PYTHON3) test_netnamespace.py
	$(PYTHON3) test_mountnamespace.py
	$(PYTHON3) test_pid_ipc_namespace.py
